# Generated by Django 2.2 on 2020-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2', '0002_auto_20200817_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postq',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
