# Generated by Django 2.2 on 2020-08-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postq',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
