# Generated by Django 2.2 on 2020-09-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r2', '0005_auto_20200818_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
